language: node_js
env:
  global:
    secure: Bn4Ylq4Bde2lvKCwRZNzSlEgrzVYM/6NpA8gim5mlUpA2AWeMB5XZV9yT4cVnxZ9Yk3CDT9ZCnpmZFd8KJP0PK3DgcdXjWaNGRml+Uc3i5TpNWQmTCVIqOTq1g8VDzeIX4IiOFwPQiVdpaplNLdUVE7c4Ktl2FV9m7XUPlP0iso=
matrix:
  include:
    - node_js: "0.10"
    - node_js: "io.js"
    - node_js: "0.12"
      env: SAUCE_LABS=true
